import { useMemo, useState } from "react";
import { useAppData } from "../AppDataContext";
import { EmptyState, PageHeader } from "../components/PageHeader";
import { filterBookings, getAvailableDates } from "../services/bookingService";
import { formatPercent } from "../utils/format";
import type { BookingCase } from "../types/booking";

export function AnalyticsPage() {
  const { bookings, loading } = useAppData(); const [date, setDate] = useState("ALL"); const dates = getAvailableDates(bookings); const data = useMemo(() => filterBookings(bookings, { date, includeChecked: true }), [bookings, date]); const average = (key: "discountPercent" | "gmPercent" | "hikePercent") => data.length ? data.reduce((sum, item) => sum + item[key], 0) / data.length : 0; return <><PageHeader eyebrow="PERFORMANCE" title="Analytics" description="A read-only view calculated from the CSV." action={<select className="date-pill" value={date} onChange={(event) => setDate(event.target.value)}><option value="ALL">All dates</option>{dates.map((item) => <option key={item} value={item}>{item}</option>)}</select>} />{loading ? <div className="loading-state">Loading booking data...</div> : data.length ? <><div className="analytics-hero"><span>Bookings in view</span><strong>{data.length}</strong><small>{date === "ALL" ? "Entire source dataset" : date}</small></div><div className="metric-grid"><Metric label="Needs Review" value={data.filter((item) => item.systemStatus === "Needs Review").length} /><Metric label="Approved" value={data.filter((item) => item.systemStatus === "Approved").length} /><Metric label="Duplicate" value={data.filter((item) => item.systemStatus === "Duplicate").length} /><Metric label="Rejected" value={data.filter((item) => item.systemStatus === "Rejected").length} /><Metric label="Avg discount" value={formatPercent(average("discountPercent"))} /><Metric label="Avg GM" value={formatPercent(average("gmPercent"))} /><Metric label="Avg hike" value={formatPercent(average("hikePercent"))} /></div><Breakdown title="Bookings by house" values={countBy(data, "houseName")} /><Breakdown title="Bookings by MM" values={countBy(data, "mm")} /><Breakdown title="Booking type" values={countBy(data, "bookingType")} /><Breakdown title="Occupancy type" values={countBy(data, "occupancyType")} /></> : <EmptyState title="No analytics data" description="There are no bookings for this date." />}</>;
}

function Metric({ label, value }: { label: string; value: number | string }) { return <div className="metric-card"><span>{label}</span><strong>{value}</strong></div>; }
function countBy(data: BookingCase[], key: "houseName" | "mm" | "bookingType" | "occupancyType") { const counts = new Map<string, number>(); data.forEach((item) => { const value = String(item[key] || "Unknown"); counts.set(value, (counts.get(value) ?? 0) + 1); }); return [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 8); }
function Breakdown({ title, values }: { title: string; values: [string, number][] }) { return <section className="breakdown"><div className="section-heading"><h2>{title}</h2><span>Top 8</span></div>{values.map(([label, value]) => <div className="bar-row" key={label}><span>{label}</span><strong>{value}</strong><i style={{ width: `${Math.max(4, (value / Math.max(...values.map((item) => item[1]), 1)) * 100)}%` }} /></div>)}</section>; }