import { useState } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { useAppData } from "../AppDataContext";
import { DetailRow, DetailSection } from "../components/DetailSection";
import { PrototypeActions } from "../components/PrototypeActions";
import { StatusBadge } from "../components/StatusBadge";
import { Toast } from "../components/Toast";
import type { ReviewAction } from "../types/booking";
import { formatCurrency, formatDateTime, formatPercent } from "../utils/format";

export function CaseDetailsPage() {
  const { id } = useParams(); const [searchParams] = useSearchParams(); const navigate = useNavigate(); const { bookings, loading, review } = useAppData(); const [toast, setToast] = useState<string | null>(null);
  const decodedId = decodeURIComponent(id ?? ""); const requestedId = searchParams.get("requestId"); const booking = bookings.find((item) => item.id === decodedId && (!requestedId || item.requestId === requestedId)) ?? bookings.find((item) => item.id === decodedId);
  if (loading) return <div className="standalone-state">Loading case...</div>;
  if (!booking) return <div className="standalone-state"><h1>Case not found</h1><Link to="/explore" className="text-link">Back to explorer</Link></div>;
  const handleAction = (label: string) => { review(booking, label as ReviewAction); setToast(`${label} recorded locally. Case marked as checked.`); window.setTimeout(() => navigate(-1), 600); };
  return <div className="detail-page"><header className="detail-header"><button type="button" onClick={() => navigate(-1)} className="back-button">Back</button><div className="detail-title-row"><div><p className="eyebrow light">CASE REVIEW</p><h1>{booking.houseName}</h1><p>{booking.mm} / Room {booking.roomNumber}</p></div><StatusBadge status={booking.systemStatus} /></div></header><main className="detail-content"><DetailSection title="Customer"><DetailRow label="Customer ID" value={booking.customerId} /><DetailRow label="Customer Phone" value={booking.customerPhone} /><DetailRow label="Name" value={booking.name ?? "-"} /></DetailSection><DetailSection title="Booking"><DetailRow label="Booking Category" value={booking.bookingCategory} /><DetailRow label="House Category" value={booking.houseCategory ?? "-"} /><DetailRow label="Booking Type" value={booking.bookingType} /><DetailRow label="Occupancy Type" value={booking.occupancyType} /><DetailRow label="Booking Tenure" value={booking.bookingTenure} /><DetailRow label="Payment Frequency" value={booking.paymentFrequency} /><DetailRow label="Beds Requested" value={String(booking.bedsRequested)} /></DetailSection><DetailSection title="Pricing"><DetailRow label="Sigma Price" value={formatCurrency(booking.sigmaPrice)} /><DetailRow label="Ask Price" value={formatCurrency(booking.askPrice)} /><DetailRow label="AMC Amount" value={formatCurrency(booking.amcAmount)} /><DetailRow label="Discount %" value={formatPercent(booking.discountPercent)} /></DetailSection><DetailSection title="Performance"><DetailRow label="GM %" value={formatPercent(booking.gmPercent)} /><DetailRow label="Hike %" value={formatPercent(booking.hikePercent)} /></DetailSection><DetailSection title="Workflow"><DetailRow label="Circle" value={booking.circle ?? "-"} /><DetailRow label="Status for Kundan" value={booking.statusForKundan ?? "-"} /><DetailRow label="Request ID" value={booking.requestId ?? "-"} /><DetailRow label="Timestamp" value={formatDateTime(booking.timestamp)} /><DetailRow label="System Status" value={booking.systemStatus} /></DetailSection><DetailSection title="Remarks"><p className="remarks-text">{booking.remarks || "No remarks provided."}</p></DetailSection></main><div className="detail-actions"><PrototypeActions onAction={handleAction} /></div>{toast ? <Toast message={toast} onDismiss={() => setToast(null)} /> : null}</div>;
}