import { useMemo, useState } from "react";
import { useAppData } from "../AppDataContext";
import { BookingCardList } from "../components/BookingCardList";
import { EmptyState, PageHeader } from "../components/PageHeader";
import { filterBookings, getAvailableDates } from "../services/bookingService";

export function ExplorerPage() {
  const { bookings, loading } = useAppData(); const [query, setQuery] = useState(""); const [date, setDate] = useState("ALL"); const [status, setStatus] = useState("All"); const [house, setHouse] = useState(""); const [mm, setMm] = useState(""); const [bookingType, setBookingType] = useState(""); const [occupancy, setOccupancy] = useState(""); const dates = getAvailableDates(bookings); const houses = [...new Set(bookings.map((item) => item.houseName).filter(Boolean))].sort(); const mms = [...new Set(bookings.map((item) => item.mm).filter(Boolean))].sort(); const types = [...new Set(bookings.map((item) => item.bookingType).filter(Boolean))].sort(); const occupancies = [...new Set(bookings.map((item) => item.occupancyType).filter(Boolean))].sort();
  const results = useMemo(() => filterBookings(bookings, { date, query, status, house, mm, bookingType, occupancyType: occupancy, includeChecked: true }), [bookings, bookingType, date, house, mm, occupancy, query, status]);
  return <><PageHeader eyebrow="ALL RECORDS" title="Booking explorer" description="Search and filter every row in the source CSV." /><div className="explorer-search"><label className="field-label">Search all booking fields<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Phone, customer ID, house, MM, room, request ID" /></label></div><div className="filter-grid"><Select label="Date" value={date} onChange={setDate} options={dates} allLabel="All dates" /><Select label="House" value={house} onChange={setHouse} options={houses} allLabel="All houses" /><Select label="MM" value={mm} onChange={setMm} options={mms} allLabel="All MMs" /><Select label="Booking type" value={bookingType} onChange={setBookingType} options={types} allLabel="All types" /><Select label="Occupancy" value={occupancy} onChange={setOccupancy} options={occupancies} allLabel="All occupancy" /><Select label="System status" value={status} onChange={setStatus} options={["Needs Review", "Approved", "Duplicate", "Rejected", "On Hold"]} allLabel="All statuses" /></div><div className="result-bar"><strong>{results.length} bookings found</strong><button type="button" className="text-button" onClick={() => { setQuery(""); setDate("ALL"); setStatus("All"); setHouse(""); setMm(""); setBookingType(""); setOccupancy(""); }}>Clear filters</button></div>{loading ? <div className="loading-state">Loading booking data...</div> : results.length ? <BookingCardList bookings={results.slice(0, 100)} /> : <EmptyState title="No bookings found" description="No source rows match this combination of filters." />}</>;
}

function Select({ label, value, onChange, options, allLabel }: { label: string; value: string; onChange: (value: string) => void; options: string[]; allLabel: string }) { return <label className="field-label">{label}<select value={value} onChange={(event) => onChange(event.target.value)}><option value="">{allLabel}</option>{options.map((item) => <option key={item} value={item}>{item}</option>)}</select></label>; }